# -*- coding: utf-8 -*-
"""MAGIC Gamma Telescope Machine Learning Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkFqcSLlEi9fK-vhYuL5KdIKNrrWeaCk

**MAGIC GAMMA TELESCOPE MACHINE LEARNING PROJECT**

Project Title: Classifying Cosmic Particle Signals using Supervised Machine Learning: A Comparative Study on the MAGIC Gamma Telescope Dataset.

Core Objective: Analyze the MAGIC Gamma Telescope dataset and build an optimized binary classification model to accurately distinguish between the following particle event classes:

Gamma Rays (g) – Signals generated by high-energy gamma particles captured by the telescope
Hadron Events (h) – Background noise caused by cosmic hadrons that must be filtered out


**Key question solved in this project**
1. What is the structure and quality of the dataset?
2. Is the dataset balanced or imbalanced?
3. Which telescope signal features are most informative?
5. Are there redundant or highly correlated variables?
6. How do feature distributions differ between Gamma and Hadron events?
7. Which machine learning model performs best for classification?
8. How accurate is the final model on unseen test data?
"""

import json
import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.base import clone
from sklearn.calibration import CalibratedClassifierCV
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE

"""**SECTION-A: LOAD THE DATASET**"""

# Load dataset
df = pd.read_csv("magic04_gamma.csv")

# Drop unwanted index column if present
if "Unnamed: 0" in df.columns:
    df = df.drop(columns=["Unnamed: 0"])

# Convert target labels into numeric form
# Gamma = 0, Hadron = 1
df["class"] = df["class"].astype(str).str.strip().str.lower().map({"g":0, "h":1})

# Show first 5 rows
df.head()

# Create compact dataset summary table
summary = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "missing_values": df.isna().sum().values,
    "missing_percentage": (df.isna().mean() * 100).round(2).values,
    "unique_values": df.nunique().values
})

summary

"""**SECTION B: Target Variable Analysis**
Distribution of Gamma (g) vs Hadron (h)

The distribution of classes affects model performance. If the dataset is imbalanced, the model may become biased toward the class with more samples.

As a result, predictions for the minority class may be less accurate. Checking class balance helps build a fair and reliable model.
"""

# TARGET VARIABLE ANALYSIS

# Create class count and percentage summary table
counts = df["class"].value_counts().sort_index()

class_distribution = pd.DataFrame({
    "class": ["Gamma", "Hadron"],
    "count": [counts.get(0, 0), counts.get(1, 0)]
})

class_distribution["percentage"] = (
    class_distribution["count"] / len(df) * 100
).round(2)

print(class_distribution)


# Plot class distribution
plt.figure(figsize=(7, 5))
bar_plot = plt.bar(
    class_distribution["class"],
    class_distribution["count"]
)

plt.title("Class Distribution: Gamma vs Hadron")
plt.xlabel("Class")
plt.ylabel("Count")

# Add percentage labels above bars
for bar, pct in zip(bar_plot, class_distribution["percentage"]):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f"{pct:.2f}%",
        ha="center",
        va="bottom"
    )

plt.tight_layout()
plt.savefig("plots/class_distribution.png", dpi=300, bbox_inches="tight")
plt.show()

"""We can see that percentage of g: 65% and percentage of h is 35%. So there exists a class imbalance.

**Handling Class Imbalance**

The dataset shows a moderate class imbalance. Although it is not extreme, it may cause the model to favor the majority class.

This problem can be handled using techniques such as Random Oversampling or SMOTE.

In this project, we use **SMOTE** to balance the training data before model building.

**SECTION C: Feature Distribution**
"""

# Select all feature columns except target
feature_columns = [col for col in df.columns if col != "class"]

# Create subplot grid
fig, axes = plt.subplots(
    len(feature_columns),
    1,
    figsize=(10, 4 * len(feature_columns))
)

# If only one feature exists, convert axes into list
if len(feature_columns) == 1:
    axes = [axes]

# Plot histogram for each feature
for ax, col in zip(axes, feature_columns):
    ax.hist(
        df[df["class"] == 0][col],
        bins=30,
        alpha=0.6,
        density=True,
        label="Gamma"
    )
    ax.hist(
        df[df["class"] == 1][col],
        bins=30,
        alpha=0.6,
        density=True,
        label="Hadron"
    )

    ax.set_title(f"Feature Distribution: {col}")
    ax.set_xlabel(col)
    ax.set_ylabel("Density")
    ax.legend()

plt.tight_layout()
plt.savefig("plots/feature_distributions.png", dpi=300, bbox_inches="tight")
plt.show()

"""SECTION C: Outlier Detection:
1. Boxplot(Visual)
2. IQR(Inter Quartile Range)
"""

# Boxplots help visually inspect skewness and extreme values.
feature_df = df.drop(columns=["class"])
melted_df = feature_df.melt(var_name="feature", value_name="value")

plt.figure(figsize=(14, 6))
sns.boxplot(data=melted_df, x="feature", y="value")
plt.xticks(rotation=45)
plt.title("Feature-wise Boxplots")
plt.tight_layout()
plt.savefig("plots/feature_boxplots.png", dpi=300, bbox_inches="tight")
plt.show()

# IQR-based outlier summary table
outlier_rows = []

for col in feature_df.columns:
    q1 = feature_df[col].quantile(0.25)
    q3 = feature_df[col].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outlier_count = ((feature_df[col] < lower_bound) | (feature_df[col] > upper_bound)).sum()
    outlier_percentage = round((outlier_count / len(feature_df)) * 100, 3)

    outlier_rows.append({
        "feature": col,
        "q1": round(q1, 3),
        "q3": round(q3, 3),
        "iqr": round(iqr, 3),
        "lower_bound": round(lower_bound, 3),
        "upper_bound": round(upper_bound, 3),
        "outlier_count": outlier_count,
        "outlier_percentage": outlier_percentage
    })

outlier_summary = pd.DataFrame(outlier_rows)

print(outlier_summary)

"""**SECTION C: Feature Relationships (Correlation Analysis)**"""

# Compute correlation matrix
correlation_matrix = df.corr()

# Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f",
    linewidths=0.5
)

plt.title("Correlation Heatmap")
plt.tight_layout()
plt.savefig("plot/correlation_heatmap.png", dpi=300, bbox_inches="tight")
plt.show()

"""Correlation analysis revealed strong relationships between several features, particularly between fConc and fConc1 (0.98), indicating redundancy. Additionally, features such as fLength, fWidth, and fSize exhibited strong inter-correlation, suggesting they capture similar characteristics. Among all features, fSize, fLength, and fWidth showed the highest correlation with the target variable, indicating strong predictive potential. Weakly correlated features such as fM3Trans may contribute independent information to the model.

Which means I can remove fconc1 or fconc. As they are redundent.

After Doing the EDA we found out the following:
1. There exists a class imbalance Percent of g:64.84% and Percentage of g: 36%.
2. From the box plot we found out that the range of these features are very large so we need to scale them.
3. From the heat map we found out that some features like fconc and fconc1 are redundent are we can drop one.

The next step of the pipeline is to divide the dataset into train, validate and test datasets. The entire dataset was then divided into 70%train, 15% validate and 15% tests dataset.

Stratified split was prefered because it preserves the ratio of train,test and validate datasets among each split.
"""

# Split dataset into input features (X) and target variable (y)
X = df.drop("class", axis=1)
y = df["class"]

# Perform stratified split:
# 70% Training Data
# 15% Validation Data
# 15% Test Data

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

# Display dataset shapes
print(f"Training set shape   : {X_train.shape}")
print(f"Validation set shape : {X_val.shape}")
print(f"Test set shape       : {X_test.shape}")

# Handling class imbalance
smote = SMOTE(random_state=42)

# Display dataset shapes before SMOTE
print("Before SMOTE")
print(f"Training set shape   : {X_train.shape}")
print(f"Validation set shape : {X_val.shape}")
print(f"Test set shape       : {X_test.shape}")

X_train, y_train = smote.fit_resample(X_train, y_train)

# Display dataset shapes after SMOTE
print("\nAfter SMOTE")
print(f"Resampled training set shape : {X_train.shape}")
print(f"Resampled target shape       : {y_train.shape}")

# StandardScaler is applied because some features have
# large value ranges and different scales.

scaler = StandardScaler()

# Fit only on training data to avoid data leakage
X_train = scaler.fit_transform(X_train)

# Apply same transformation to validation and test sets
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Confirm scaling results
print("Mean of scaled training data :", round(X_train.mean(), 4))
print("Std of scaled training data  :", round(X_train.std(), 4))

"""SECTION : BUILD MODELS"""

# Building models
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        random_state=42
    ),

    "Gaussian Naive Bayes": GaussianNB(),

    "Linear SVM": LinearSVC(
        random_state=42,
        max_iter=5000
    ),

    "Decision Tree": DecisionTreeClassifier(
        random_state=42
    ),

    "Random Forest": RandomForestClassifier(
        random_state=42
    ),

    "Gradient Boosting": GradientBoostingClassifier(
        random_state=42
    ),

    "Voting Classifier": VotingClassifier(
        estimators=[
            ("lr", LogisticRegression()),
            ("svm", SVC(probability=True)),
            ("rf", RandomForestClassifier())
        ],
        voting="soft"
    )
}

print("Models built successfully:")
for model_name in models.keys():
    print("-", model_name)

"""**SECTION D: MODEL EVALUATION ON VALIDATION DATA**"""

# MODEL EVALUATION ON VALIDATION DATA


# Train each model and evaluate on validation data
rows = []
fitted_models = {}

for model_name, model in models.items():
    # Train model
    model.fit(X_train, y_train)

    # Predict class labels
    y_pred = model.predict(X_val)

    # Predict probabilities for ROC-AUC
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_val)[:, 1]
    elif hasattr(model, "decision_function"):
        y_prob = model.decision_function(X_val)
    else:
        y_prob = y_pred

    # Store evaluation metrics
    rows.append({
        "model": model_name,
        "accuracy": round(accuracy_score(y_val, y_pred), 4),
        "precision": round(precision_score(y_val, y_pred), 4),
        "recall": round(recall_score(y_val, y_pred), 4),
        "f1_score": round(f1_score(y_val, y_pred), 4),
        "roc_auc": round(roc_auc_score(y_val, y_prob), 4)
    })

    # Save fitted model
    fitted_models[model_name] = model

# Create results dataframe
results_df = pd.DataFrame(rows).sort_values(
    by=["f1_score", "roc_auc", "accuracy"],
    ascending=False
)

# Display results
print("Validation Results:")
print(results_df)

# Save results table
results_df.to_csv("plots/model_validation_results.csv", index=False)

# SECTION M: MODEL COMPARISON VISUALIZATION

plt.figure(figsize=(10, 6))
plot_df = results_df.sort_values(by="f1_score")
plt.barh(plot_df["model"], plot_df["f1_score"])

plt.title("Validation F1 Score by Model")
plt.xlabel("F1 Score")
plt.ylabel("Model")

# Add score labels on bars
for i, v in enumerate(plot_df["f1_score"]):
    plt.text(v, i, f" {v:.4f}", va="center")

plt.tight_layout()
plt.savefig("plots/validation_model_comparison.png", dpi=300, bbox_inches="tight")
plt.show()

# SECTION: FINAL TEST EVALUATION

# Select best model based on validation F1 score
best_model_name = results_df.iloc[0]["model"]
best_model = fitted_models[best_model_name]

print(f"Best Model Selected: {best_model_name}")

# Predict on unseen test data
y_test_pred = best_model.predict(X_test)

# Probability scores for ROC-AUC
if hasattr(best_model, "predict_proba"):
    y_test_prob = best_model.predict_proba(X_test)[:, 1]
elif hasattr(best_model, "decision_function"):
    y_test_prob = best_model.decision_function(X_test)
else:
    y_test_prob = y_test_pred

# Calculate test metrics
test_metrics = pd.DataFrame([{
    "best_model": best_model_name,
    "accuracy": round(accuracy_score(y_test, y_test_pred), 4),
    "precision": round(precision_score(y_test, y_test_pred), 4),
    "recall": round(recall_score(y_test, y_test_pred), 4),
    "f1_score": round(f1_score(y_test, y_test_pred), 4),
    "roc_auc": round(roc_auc_score(y_test, y_test_prob), 4)
}])

print("\nTest Set Metrics:")
print(test_metrics)

# Save results
test_metrics.to_csv("test_metrics.csv", index=False)

# Detailed classification report
print("\nDetailed Classification Report:")
print(
    classification_report(
        y_test,
        y_test_pred,
        target_names=["Gamma", "Hadron"]
    )
)

# SECTION: CONFUSION MATRIX

print("\n" + "=" * 70)
print("SECTION O: CONFUSION MATRIX")
print("=" * 70)

# Create confusion matrix
cm = confusion_matrix(y_test, y_test_pred)

# Plot confusion matrix
fig, ax = plt.subplots(figsize=(6, 5))

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Gamma", "Hadron"]
).plot(ax=ax, colorbar=False)

plt.title("Confusion Matrix - Best Model")
plt.tight_layout()
plt.savefig("plots/best_model_confusion_matrix.png", dpi=300, bbox_inches="tight")
plt.show()

# SECTION P: ROC CURVE

# Calculate ROC values
fpr, tpr, _ = roc_curve(y_test, y_test_prob)
roc_auc = roc_auc_score(y_test, y_test_prob)

# Plot ROC Curve
plt.figure(figsize=(7, 5))

plt.plot(
    fpr,
    tpr,
    label=f"ROC AUC = {roc_auc:.4f}"
)

plt.plot([0, 1], [0, 1], linestyle="--")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Best Model")
plt.legend()

plt.tight_layout()
plt.savefig("plots/best_model_roc_curve.png", dpi=300, bbox_inches="tight")
plt.show()

# ============================================================
# SECTION Q: PRECISION RECALL CURVE
# ============================================================

print("\n" + "=" * 70)
print("SECTION Q: PRECISION RECALL CURVE")
print("=" * 70)

# Calculate precision-recall values
precision_vals, recall_vals, _ = precision_recall_curve(y_test, y_test_prob)

# Plot Precision-Recall Curve
plt.figure(figsize=(7, 5))

plt.plot(recall_vals, precision_vals)

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve - Best Model")

plt.tight_layout()
plt.savefig("plots/best_model_precision_recall_curve.png", dpi=300, bbox_inches="tight")
plt.show()

import shutil
from google.colab import files

shutil.make_archive("plots", "zip", "plots")
files.download("plots.zip")

